config/routes.rb
Rails.application.routes.draw do
  root to: 'owners#index'
  resources :owners
  
  get '/owners/:id/update_cats_status', to: 'owners#updatecatstatus', as: :update_cats_status
  get '/owners/:id/update_dogs_status', to: 'owners#updatedogsstatus', as: :update_dogs_status
end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/models/cats_owner.rb
class CatsOwner < ActiveRecord::Base
  belongs_to :cat
  belongs_to :owner
end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/models/dogs_owner.rb
class DogsOwner < ActiveRecord::Base
  belongs_to :dog
  belongs_to :owner
end

app/models/drink.rb
class Drink < ActiveRecord::Base
	belongs_to :answer
end

app/models/food.rb
class Food < ActiveRecord::Base
	belongs_to :answer
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :cats_owners
  has_many :cats, through: :cats_owners

  has_many :dogs_owners
  has_many :dogs, through: :dogs_owners
  
  accepts_nested_attributes_for :cats_owners, allow_destroy: true
  accepts_nested_attributes_for :dogs_owners, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # update cats status
  def updatecatstatus
    @owners = Owner.all
    owner_id = Owner.find(params[:id])
    CatsOwner.where(owner_id: owner_id).update_all(:status => 1)
    redirect_to action: "index"
  end

  def updatedogsstatus
    @owners = Owner.all
    owner_id = Owner.find(params[:id])
    DogsOwner.where(owner_id: owner_id).update_all(:status => 1)
    redirect_to action: "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, cats_owners_attributes: [:id, :quantity, :status, :cat_id ,:_destroy], dogs_owners_attributes: [:id, :quantity, :status, :dog_id, :_destroy])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
    	new_object = f.object.send(association).klass.new
    	id = new_object.object_id
	    fields = f.fields_for(association, new_object, child_index: id) do |builder|
	      render(association.to_s.singularize + "_fields", f: builder)
	    end
    	link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questionnaire</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/owners/_cats_owner_fields.html.erb
<br/>
  <%= f.label :cat %>
  <%= f.select :cat_id, options_for_select(Cat.all.map{|c| [c.name, c.id]}, f.object.cat_id)%>
  
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>

  <%= f.label :status %>
  <%= f.text_field :status %>

  <%= f.check_box :_destroy %><%= f.label :_destroy, "Remove Cat" %><br>

app/views/owners/_dogs_owner_fields.html.erb
<br/>
  <%= f.label :dog %>
  <%= f.select :dog_id, options_for_select(Dog.all.map{|d| [d.name, d.id]}, f.object.dog_id)%>
  
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>

  <%= f.label :status %>
  <%= f.text_field :status %>

  <%= f.check_box :_destroy %><%= f.label :_destroy, "Remove Dog" %><br>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>

  <%= f.text_field :name %>

  <h4> Add Cats </h4>
  <%= f.fields_for :cats_owners do |co| %>
    <%= render 'cats_owner_fields', f: co %>
  <% end %>
  <%= link_to_add_fields "Add Cat", f, :cats_owners %>
  
  <h4> Add Dogs</h4>
  <%= f.fields_for :dogs_owners do |co| %>
    <%= render 'dogs_owner_fields', f: co %>
  <% end %>
  <%= link_to_add_fields "Add Dog", f, :dogs_owners %>

  <br><br>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing Owners</h1>

<table border="1">
  <thead>
    <tr>
      <th>Owners</th>
      <th>Cats</th>
      <th>Dogs</th>
      <th colspan="5">Action</th>
    </tr>
  </thead>

  <tbody>
    
      <% @owners.each do |owner| %>
      <% if owner.cats_owners.first.status == 0 %>
        <tr>
          <td><%= owner.name %></td>
          <td>
            <% owner.cats_owners.each do |c| %>
              <p><%= c.cat.name %> | Qty: <%= c.quantity %> | Status: <%= c.status %></p>
            <% end %>
          </td>
          <td>
            <% owner.dogs_owners.each do |d| %>
              <p><%= d.dog.name %> | Qty: <%= d.quantity %> | Status: <%= d.status %></p>
            <% end %>
          </td>
          <td><%= link_to 'Show', owner %></td>
          <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
          <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Update cats status', update_cats_status_path(:id => owner.id) %></td>
          <td><%= link_to 'Update dogs status', update_dogs_status_path(:id => owner.id) %></td>
        </tr>
      <% end %>
      <% end %>
    
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<h1>
  <%= @owner.name %>
</h1>

<% if @owner.cats_owners.present? %>
  <h3>Cats: </h3>
  <ul>
    <% @owner.cats_owners.each do |co| %> 
      <li><%= co.cat.name %> | Quantity: <%= co.quantity%> | Status: <%= co.status%></li>
    <% end %>
  </ul>
<% end %>
  
<% if @owner.dogs_owners.present? %>
<h3>Dogs: </h3>
  <ul>
    <% @owner.dogs_owners.each do |co| %> 
      <li><%= co.dog.name %> | Quantity: <%= co.quantity%> | Status: <%= co.status%></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>